--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINISTRADOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMI"."ADMINISTRADOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR
--------------------------------------------------------

  CREATE TABLE "ADMI"."ADMINISTRADOR" 
   (	"ID_ADMINISTRADOR" NUMBER, 
	"NOMBRE_ADMINISTRADOR" VARCHAR2(20 BYTE), 
	"APELLIDO_ADMINISTRADOR" VARCHAR2(20 BYTE), 
	"CORREO_ADMINISTRADOR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR_CLIENTE
--------------------------------------------------------

  CREATE TABLE "ADMI"."ADMINISTRADOR_CLIENTE" 
   (	"ID_ADMINISTRADOR" NUMBER, 
	"ID_CLIENTE" NUMBER, 
	"ID_ADMINISTRADOR_CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR_VIDEOJUEGO
--------------------------------------------------------

  CREATE TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" 
   (	"ID_ADMINISTRADOR" NUMBER, 
	"ID_VIDEOJUEGO" NUMBER, 
	"ID_ADMINISTRADOR_VIDEOJUEGO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "ADMI"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"NOMBRE_CLIENTE" VARCHAR2(20 BYTE), 
	"APELLIDO_CLIENTE" VARCHAR2(20 BYTE), 
	"CORREO_CLIENTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VIDEOJUEGO
--------------------------------------------------------

  CREATE TABLE "ADMI"."VIDEOJUEGO" 
   (	"ID_VIDEOJUEGO" NUMBER, 
	"NOMBRE_VIDEOJUEGO" VARCHAR2(20 BYTE), 
	"CATEGORIA_VIDOJUEGO" VARCHAR2(20 BYTE), 
	"PESO_VIDEOJUEGO" VARCHAR2(20 BYTE), 
	"CATEGORIA_EDAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ADMI.ADMINISTRADOR
SET DEFINE OFF;
Insert into ADMI.ADMINISTRADOR (ID_ADMINISTRADOR,NOMBRE_ADMINISTRADOR,APELLIDO_ADMINISTRADOR,CORREO_ADMINISTRADOR) values ('25','juan','garcia','juanGarcia@gmail.com');
Insert into ADMI.ADMINISTRADOR (ID_ADMINISTRADOR,NOMBRE_ADMINISTRADOR,APELLIDO_ADMINISTRADOR,CORREO_ADMINISTRADOR) values ('1','Rafael','Ruge','Rafaelruge@gmail.com');
REM INSERTING into ADMI.ADMINISTRADOR_CLIENTE
SET DEFINE OFF;
Insert into ADMI.ADMINISTRADOR_CLIENTE (ID_ADMINISTRADOR,ID_CLIENTE,ID_ADMINISTRADOR_CLIENTE) values ('1',null,'1');
Insert into ADMI.ADMINISTRADOR_CLIENTE (ID_ADMINISTRADOR,ID_CLIENTE,ID_ADMINISTRADOR_CLIENTE) values ('25','2','2');
REM INSERTING into ADMI.ADMINISTRADOR_VIDEOJUEGO
SET DEFINE OFF;
Insert into ADMI.ADMINISTRADOR_VIDEOJUEGO (ID_ADMINISTRADOR,ID_VIDEOJUEGO,ID_ADMINISTRADOR_VIDEOJUEGO) values ('1','1','1');
REM INSERTING into ADMI.CLIENTE
SET DEFINE OFF;
Insert into ADMI.CLIENTE (ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,CORREO_CLIENTE) values ('2','jose d','cruz','josecruz@gmail.com');
Insert into ADMI.CLIENTE (ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,CORREO_CLIENTE) values ('3','joselino','penagos','gozelino');
Insert into ADMI.CLIENTE (ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,CORREO_CLIENTE) values ('45','Pedro','Lamas','HOLa@hotmail.com');
Insert into ADMI.CLIENTE (ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,CORREO_CLIENTE) values ('6','juan pablo','gimenez','juanito@gmail.com');
REM INSERTING into ADMI.VIDEOJUEGO
SET DEFINE OFF;
Insert into ADMI.VIDEOJUEGO (ID_VIDEOJUEGO,NOMBRE_VIDEOJUEGO,CATEGORIA_VIDOJUEGO,PESO_VIDEOJUEGO,CATEGORIA_EDAD) values ('1','wow','rpg','25 gb','TP');
Insert into ADMI.VIDEOJUEGO (ID_VIDEOJUEGO,NOMBRE_VIDEOJUEGO,CATEGORIA_VIDOJUEGO,PESO_VIDEOJUEGO,CATEGORIA_EDAD) values ('3','lol','accion','45 gb','PG 12');
Insert into ADMI.VIDEOJUEGO (ID_VIDEOJUEGO,NOMBRE_VIDEOJUEGO,CATEGORIA_VIDOJUEGO,PESO_VIDEOJUEGO,CATEGORIA_EDAD) values ('5','Call of dutty','accion','65 gb','PG 18');
Insert into ADMI.VIDEOJUEGO (ID_VIDEOJUEGO,NOMBRE_VIDEOJUEGO,CATEGORIA_VIDOJUEGO,PESO_VIDEOJUEGO,CATEGORIA_EDAD) values ('16','Assassin''s creed ','Aventura','54 gb','PG 17');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMI"."TABLE1_PK" ON "ADMI"."ADMINISTRADOR" ("ID_ADMINISTRADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRADOR_VIDEOJUEGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMI"."ADMINISTRADOR_VIDEOJUEGO_PK" ON "ADMI"."ADMINISTRADOR_VIDEOJUEGO" ("ID_ADMINISTRADOR_VIDEOJUEGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VIDEOJUEGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMI"."VIDEOJUEGO_PK" ON "ADMI"."VIDEOJUEGO" ("ID_VIDEOJUEGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMI"."CLIENTE_PK" ON "ADMI"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRADOR_CLIENTE_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMI"."ADMINISTRADOR_CLIENTE_PK1" ON "ADMI"."ADMINISTRADOR_CLIENTE" ("ID_ADMINISTRADOR_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR_CLIENTE
--------------------------------------------------------

  ALTER TABLE "ADMI"."ADMINISTRADOR_CLIENTE" MODIFY ("ID_ADMINISTRADOR_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR_CLIENTE" ADD CONSTRAINT "ADMINISTRADOR_CLIENTE_PK" PRIMARY KEY ("ID_ADMINISTRADOR_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "ADMI"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMI"."CLIENTE" MODIFY ("CORREO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."CLIENTE" MODIFY ("APELLIDO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."CLIENTE" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR_VIDEOJUEGO
--------------------------------------------------------

  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" ADD CONSTRAINT "ADMINISTRADOR_VIDEOJUEGO_PK" PRIMARY KEY ("ID_ADMINISTRADOR_VIDEOJUEGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" MODIFY ("ID_ADMINISTRADOR_VIDEOJUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" MODIFY ("ID_VIDEOJUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" MODIFY ("ID_ADMINISTRADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "ADMI"."ADMINISTRADOR" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_ADMINISTRADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMI"."ADMINISTRADOR" MODIFY ("CORREO_ADMINISTRADOR" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR" MODIFY ("APELLIDO_ADMINISTRADOR" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR" MODIFY ("NOMBRE_ADMINISTRADOR" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."ADMINISTRADOR" MODIFY ("ID_ADMINISTRADOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VIDEOJUEGO
--------------------------------------------------------

  ALTER TABLE "ADMI"."VIDEOJUEGO" ADD CONSTRAINT "VIDEOJUEGO_PK" PRIMARY KEY ("ID_VIDEOJUEGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMI"."VIDEOJUEGO" MODIFY ("CATEGORIA_EDAD" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."VIDEOJUEGO" MODIFY ("PESO_VIDEOJUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."VIDEOJUEGO" MODIFY ("CATEGORIA_VIDOJUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."VIDEOJUEGO" MODIFY ("NOMBRE_VIDEOJUEGO" NOT NULL ENABLE);
  ALTER TABLE "ADMI"."VIDEOJUEGO" MODIFY ("ID_VIDEOJUEGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRADOR_CLIENTE
--------------------------------------------------------

  ALTER TABLE "ADMI"."ADMINISTRADOR_CLIENTE" ADD CONSTRAINT "ADMINISTRADOR_CLIENTE_FK1" FOREIGN KEY ("ID_ADMINISTRADOR")
	  REFERENCES "ADMI"."ADMINISTRADOR" ("ID_ADMINISTRADOR") ENABLE;
  ALTER TABLE "ADMI"."ADMINISTRADOR_CLIENTE" ADD CONSTRAINT "ADMINISTRADOR_CLIENTE_FK2" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "ADMI"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRADOR_VIDEOJUEGO
--------------------------------------------------------

  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" ADD CONSTRAINT "ADMINISTRADOR_VIDEOJUEGO_FK1" FOREIGN KEY ("ID_ADMINISTRADOR")
	  REFERENCES "ADMI"."ADMINISTRADOR" ("ID_ADMINISTRADOR") ENABLE;
  ALTER TABLE "ADMI"."ADMINISTRADOR_VIDEOJUEGO" ADD CONSTRAINT "ADMINISTRADOR_VIDEOJUEGO_FK2" FOREIGN KEY ("ID_VIDEOJUEGO")
	  REFERENCES "ADMI"."VIDEOJUEGO" ("ID_VIDEOJUEGO") ENABLE;
