CREATE TABLE ADMINISTRADOR 
(
  ID NUMBER NOT NULL 
, NOMBRE_ADMIN VARCHAR2(20) NOT NULL 
, APELLIDO_ADMIN VARCHAR2(20) NOT NULL 
, CORREO_ADMIN VARCHAR2(20) NOT NULL 
, CONTRAEÑA_ADMIN VARCHAR2(20) NOT NULL 
, CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE VIDEOJUEGOS 
(
  ID NUMBER NOT NULL 
, NOMBRE_DEL_VIDEOJUEGO VARCHAR2(20) NOT NULL 
, CATEGORIA_DEL_VIDEOJUEGO VARCHAR2(20) NOT NULL 
, PESO_EN_GB_DEL_VIDEOJUEGO VARCHAR2(20) NOT NULL 
, CATEGORIA_EDAD VARCHAR2(20) NOT NULL 
, CONSTRAINT VIDEOJUEGOS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE VIDEOJUAEGO_Y_GENEROS 
(
  ID NUMBER NOT NULL 
, ID_VIDEOJUEGOS NUMBER NOT NULL 
, ID_GENEROS NUMBER NOT NULL 
, CONSTRAINT VIDEOJUAEGO_Y_GENEROS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE GENEROS 
(
  ID NUMBER NOT NULL 
, ACCION VARCHAR2(20) NOT NULL 
, AVENTURA VARCHAR2(20) NOT NULL 
, TERROR VARCHAR2(20) NOT NULL 
, MMORPG VARCHAR2(20) NOT NULL 
, CONSTRAINT GENEROS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE CATEGORIA_EDAD 
(
  ID NUMBER NOT NULL 
, EC NUMBER NOT NULL 
, E NUMBER NOT NULL 
, T NUMBER NOT NULL 
, M NUMBER NOT NULL 
, AO NUMBER NOT NULL 
, RP NUMBER NOT NULL 
, CONSTRAINT CATEGORIA_EDAD_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE CLIENTE 
(
  ID NUMBER NOT NULL 
, NOMBRE_CLIE VARCHAR2(20) NOT NULL 
, APELLIDO_CLIE VARCHAR2(20) NOT NULL 
, CORREO_CLIE VARCHAR2(20) 
, CONTRASEÑA_CLIE VARCHAR2(20) NOT NULL 
, CONSTRAINT CLIENTE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);